name: Deployment

on:
  push:
    branches: [master] # only push events on source branch trigger deployment

jobs:
  hexo-deployment:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai

    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install dependencies & Generate static files
      run: |
        node -v
        npm i -g hexo-cli
        npm i
        hexo clean
        hexo g
    - name: Deploy to Github Pages
      env:
        REPO: git@github.com:raoyingjun/raoyingjun.github.io.git
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        cd ./public && git init && git add .
        git config --global user.name Royin
        git config --global user.email raoyingjun@foxmail.com
        git commit -m "Site deployed by GitHub Actions"
        git push "https://$GH_TOKEN@$REPO" master:master
